.TH "Aplicacion/Configuracion/AppConfig.h" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aplicacion/Configuracion/AppConfig.h \- Archivo de configuracion para la aplicacion\&. Se declaran los componentes necesarios para su funcionamiento\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br
\fC#include <Clock\&.h>\fP
.br
\fC#include <Gpio\&.h>\fP
.br
\fC#include <timer_config\&.h>\fP
.br
\fC#include <Dht11\&.h>\fP
.br
\fC#include <Hx711\&.h>\fP
.br
\fC#include <rs485\&.h>\fP
.br
\fC#include <utils\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDHT11_t\fP \fBSensorTempHum\fP"
.br
.ti -1c
.RI "\fBHX711_t\fP \fBSensorPesaje\fP"
.br
.ti -1c
.RI "\fBTimer_t\fP \fBtimer_Timeout\fP"
.br
.ti -1c
.RI "\fBTimeout_t\fP \fBTimeout\fP"
.br
.ti -1c
.RI "\fBRS485_t\fP \fBComunicacion\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Archivo de configuracion para la aplicacion\&. Se declaran los componentes necesarios para su funcionamiento\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
