.TH "Referencia del directorio Communication/RS485/Ordenes" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio Communication/RS485/Ordenes
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBRS485_Ordenes\&.h\fP"
.br
.in -1c
