.TH "Referencia del directorio Communication/RS485" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio Communication/RS485
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBOrdenes\fP"
.br
.ti -1c
.RI "directorio \fBTramas\fP"
.br
.in -1c
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBRS485\&.c\fP"
.br
.ti -1c
.RI "archivo \fBRS485\&.h\fP"
.br
.ti -1c
.RI "archivo \fBRS485_Config\&.h\fP"
.br
.in -1c
