.TH "Referencia del directorio Aplicacion/Configuracion" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio Aplicacion/Configuracion
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBAppConfig\&.h\fP"
.br
.RI "Archivo de configuracion para la aplicacion\&. Se declaran los componentes necesarios para su funcionamiento\&. "
.in -1c
