.TH "Referencia del directorio KICAD/Librerias/LIB_STM8S103F3P3/STM8S103F3P3/PADS" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio KICAD/Librerias/LIB_STM8S103F3P3/STM8S103F3P3/PADS
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBSOP65P640X120\-20N\&.d\fP"
.br
.ti -1c
.RI "archivo \fBSTM8S103F3P3\&.c\fP"
.br
.in -1c
