.TH "Referencia del directorio Api/N_HAL/Utils" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio Api/N_HAL/Utils
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fButils\&.h\fP"
.br
.RI "Define distintas funciones, macros utiles\&. "
.in -1c
