.TH "DHT11_Config" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DHT11_Config \- Define los pines elegidos para comunicar con el sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht11\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBGpio_Config_t\fP \fBHW\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Define los pines elegidos para comunicar con el sensor\&. 


.PP
\fBVer también\fP
.RS 4
\fBGpio_Config_t\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBGpio_Config_t\fP HW"
Configuracion de los pine 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
