.TH "Drivers/DHT11/dht11.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/DHT11/dht11.c
.SH SYNOPSIS
.br
.PP
\fC#include <dht11\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBDHT11_Init\fP (\fBDHT11_t_ptr\fP dht11, \fBDHT11_fPtr\fP Lectura, \fBTimeout_t_ptr\fP \fBTimeout\fP)"
.br
.ti -1c
.RI "\fBDHT11_SI_t\fP \fBdht11_Lectura\fP (\fBDHT11_t_ptr\fP dht11)"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
