.TH "DHT11" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DHT11 \- Define el objeto principal para interactuar con un sensor \fBDHT11\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht11\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBDHT11_Config_t\fP \fBConfig\fP"
.br
.ti -1c
.RI "\fBDHT11_Datos_t\fP \fBDatos\fP"
.br
.ti -1c
.RI "\fBTimeout_t_ptr\fP \fBTimeout\fP"
.br
.ti -1c
.RI "\fBDHT11_fPtr\fP \fBLectura\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Define el objeto principal para interactuar con un sensor \fBDHT11\fP\&. 


.PP
\fBVer también\fP
.RS 4
\fBDHT11_Config_t\fP 
.PP
\fBDHT11_Datos_t\fP 
.PP
\fBDHT11_fPtr\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBDHT11_Config_t\fP Config"
Configuracion del sensor 
.SS "\fBDHT11_Datos_t\fP Datos"
Datos del sensor 
.SS "\fBDHT11_fPtr\fP Lectura"
Puntero a la funcion de lectura 
.SS "\fBTimeout_t_ptr\fP \fBTimeout\fP"
Sin descripcion 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
