.TH "FSM_Trama_RX" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSM_Trama_RX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485_Tramas\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBpasoActual\fP"
.br
.ti -1c
.RI "uint8_t \fBtransicion\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_Paso\fP \fBLecturaNodo\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_Paso\fP \fBLecturaOrdenDHT11\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_Paso\fP \fBLecturaOrdenHX711\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "struct \fBFSM_Trama_Paso\fP LecturaNodo"

.SS "struct \fBFSM_Trama_Paso\fP LecturaOrdenDHT11"

.SS "struct \fBFSM_Trama_Paso\fP LecturaOrdenHX711"

.SS "uint8_t pasoActual"

.SS "uint8_t transicion"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
