.TH "Api/N_HAL/Gpio/Gpio.h" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Api/N_HAL/Gpio/Gpio.h \- Este archivo contiene las operaciones basicas sobre los puertos gpio\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <Gpio_Config\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBNHALgpio_Init\fP (\fBGpio_Config_t\fP *gpio)"
.br
.ti -1c
.RI "bool \fBNHALgpio_Read\fP (\fBGpio_Config_t\fP *gpio)"
.br
.ti -1c
.RI "void \fBNHALgpio_Write\fP (\fBGpio_Config_t\fP *gpio, bool estado)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este archivo contiene las operaciones basicas sobre los puertos gpio\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
