.TH "Api/N_HAL/Gpio/Gpio_Config.h" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Api/N_HAL/Gpio/Gpio_Config.h \- Este archivo define los datos necesarios de configuracion gpio\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBGpio_Config\fP"
.br
.RI "
.br
 "
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBGpio_Config\fP \fBGpio_Config_t\fP"
.br
.RI "
.br
 "
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBNHALgpioConfig_SetType\fP (\fBGpio_Config_t\fP *gpio, GPIO_Mode_TypeDef nuevoTipo)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este archivo define los datos necesarios de configuracion gpio\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
