.TH "Gpio_Config" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gpio_Config \- 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gpio_Config\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "GPIO_TypeDef * \fBPuerto\fP"
.br
.ti -1c
.RI "GPIO_Pin_TypeDef \fBPin\fP"
.br
.ti -1c
.RI "GPIO_Mode_TypeDef \fBTipo\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.br
 


.PP
\fBVer también\fP
.RS 4
GPIO_TypeDef 
.PP
GPIO_Pin_TypeDef 
.PP
GPIO_Mode_TypeDef 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "GPIO_Pin_TypeDef Pin"

.SS "GPIO_TypeDef* Puerto"

.SS "GPIO_Mode_TypeDef Tipo"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
