.TH "Api/N_HAL/Gpio/Gpio_Config.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Api/N_HAL/Gpio/Gpio_Config.c \- Este archivo contiene operaciones de configuracion gpio\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Gpio_Config\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBNHALgpioConfig_SetType\fP (\fBGpio_Config_t\fP *gpio, GPIO_Mode_TypeDef nuevoTipo)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este archivo contiene operaciones de configuracion gpio\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
