.TH "HX711_Datos" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HX711_Datos \- Contiene los datos que podemos obtener dle hx711\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hx711\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint32_t \fBUltimaLectura\fP"
.br
.ti -1c
.RI "\fBHX711_Estado_e\fP \fBEstado\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Contiene los datos que podemos obtener dle hx711\&. 


.PP
\fBVer también\fP
.RS 4
\fBHX711_Estado_e\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBHX711_Estado_e\fP Estado"
Como se encuentra 
.SS "uint32_t UltimaLectura"
Resultado de la ultima lectura 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
