.TH "interrupt_vector" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interrupt_vector
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "unsigned char \fBinterrupt_instruction\fP"
.br
.ti -1c
.RI "\fBinterrupt_handler_t\fP \fBinterrupt_handler\fP"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "\fBinterrupt_handler_t\fP interrupt_handler"

.SS "unsigned char interrupt_instruction"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
