.TH "main.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- Ejecucion del trabajo a realizar\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br
\fC#include <AppConfig\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Rutina principal /* /*\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Ejecucion del trabajo a realizar\&. 


.SH "Documentación de las funciones"
.PP 
.SS "int main ()"

.PP
Rutina principal /* /*\&. /* /* 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
