.TH "ORDENES" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ORDENES \- ORDENES
.SH SYNOPSIS
.br
.PP
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBRS485_Orden\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBRS485_ORDENES_BYTES\fP   2"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBRS485_Orden\fP \fBRS485_Orden_t\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "#define RS485_ORDENES_BYTES   2"

.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef struct \fBRS485_Orden\fP \fBRS485_Orden_t\fP"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
