.TH "Punteros" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Punteros \- Punteros
.SH SYNOPSIS
.br
.PP
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef uint16_t(* \fBHX711_fPtr\fP) (\fBHX711_t\fP *)"
.br
.ti -1c
.RI "typedef \fBHX711_t\fP * \fBHX711_t_ptr\fP"
.br
.RI "Puntero al tipo HX711_t\&. "
.ti -1c
.RI "typedef \fBHX711_Datos_t\fP * \fBHX711_Datos_t_ptr\fP"
.br
.RI "Puntero al tipo HX711_t\&. "
.ti -1c
.RI "typedef \fBHX711_Config_t\fP * \fBHX711_Config_t_ptr\fP"
.br
.RI "Puntero al tipo HX711_t\&. "
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'typedefs'"
.PP 
.SS "\fBHX711_Config_t\fP * \fBHX711_Config_t_ptr\fP"

.PP
Puntero al tipo HX711_t\&. 
.SS "\fBHX711_Datos_t\fP * \fBHX711_Datos_t_ptr\fP"

.PP
Puntero al tipo HX711_t\&. 
.SS "typedef uint16_t(* HX711_fPtr) (\fBHX711_t\fP *)"

.SS "\fBHX711_t\fP * \fBHX711_t_ptr\fP"

.PP
Puntero al tipo HX711_t\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
