.TH "RS485_Flags_u" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RS485_Flags_u
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485\&.h>\fP
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBflagBit\fP"
.br
.in -1c
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.ti -1c
.RI "struct \fBRS485_Flags_u::flagBit\fP \fBbit\fP"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "struct \fBRS485_Flags_u::flagBit\fP bit"

.SS "uint8_t flags"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
