.TH "Communication/RS485/Tramas/RS485_Tramas.h" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communication/RS485/Tramas/RS485_Tramas.h
.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br
\fC#include <rs485_ordenes\&.h>\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBFSM_Trama_Paso\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_RX\fP"
.br
.ti -1c
.RI "struct \fBTrama_RX\fP"
.br
.ti -1c
.RI "struct \fBTrama_TX\fP"
.br
.ti -1c
.RI "struct \fBTrama_BROADCAST\fP"
.br
.ti -1c
.RI "struct \fBBuffer_Tramas\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBRS485_BYTES_N_NODO\fP   2"
.br
.ti -1c
.RI "#define \fBRS485_BYTES_BUFFER_RX\fP   6"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBTrama_RX\fP \fBTrama_RX_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBTrama_TX\fP \fBTrama_TX_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBTrama_BROADCAST\fP \fBTrama_BROADCAST_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBBuffer_Tramas\fP \fBBuffer_Tramas_t\fP"
.br
.RI "<descripcion> "
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
