.TH "RS485_Orden" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RS485_Orden
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485_Ordenes\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBFuncion\fP"
.br
.ti -1c
.RI "uint8_t \fBComando\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "uint8_t Comando"

.SS "uint8_t Funcion"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
