.TH "RS485_Flags_u::flagBit" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RS485_Flags_u::flagBit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBNuevaRecepcion\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBInicializado\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBStandby\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbit3\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbit4\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbit5\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbit6\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBbit7\fP: 1"
.br
.in -1c
.SH "Documentación de los campos"
.PP 
.SS "uint8_t bit3"

.SS "uint8_t bit4"

.SS "uint8_t bit5"

.SS "uint8_t bit6"

.SS "uint8_t bit7"

.SS "uint8_t Inicializado"

.SS "uint8_t NuevaRecepcion"

.SS "uint8_t Standby"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
