.TH "Communication/RS485/RS485.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communication/RS485/RS485.c
.SH SYNOPSIS
.br
.PP
\fC#include <RS485\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBRS485_Init\fP (\fBRS485_t_ptr\fP rs485)"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
