.TH "sDht11Datos" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sDht11Datos \- Define la composicion de datos del sensor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dht11\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBDHT11_SI_t\fP \fBUltimaLectura\fP"
.br
.ti -1c
.RI "\fBDHT11_Estado_e\fP \fBEstado\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Define la composicion de datos del sensor\&. 


.PP
\fBVer también\fP
.RS 4
\fBDHT11_SI_t\fP 
.PP
\fBDHT11_Estado_e\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBDHT11_Estado_e\fP Estado"
Estado del sensor 
.SS "\fBDHT11_SI_t\fP UltimaLectura"
Buffer de la ultima lectura 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
