.TH "KICAD/Librerias/LIB_STM8S103F3P3/STM8S103F3P3/PADS/SOP65P640X120-20N.d" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KICAD/Librerias/LIB_STM8S103F3P3/STM8S103F3P3/PADS/SOP65P640X120-20N.d
.SH SYNOPSIS
.br
.PP
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
