.TH "stm8_interrupt_vector.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stm8_interrupt_vector.c
.SH SYNOPSIS
.br
.PP
\fC#include <stm8s_itc\&.h>\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBinterrupt_vector\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef void far(* \fBinterrupt_handler_t\fP) (void)"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "far interrupt void \fBNonHandledInterrupt\fP (void)"
.br
.ti -1c
.RI "void \fB_stext\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBinterrupt_vector\fP const \fB_vectab\fP []"
.br
.in -1c
.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef void far(* interrupt_handler_t) (void)"
includes agregados por mi 
.SH "Documentación de las funciones"
.PP 
.SS "void _stext ()"

.SS "far interrupt void NonHandledInterrupt (void)"

.SH "Documentación de las variables"
.PP 
.SS "struct \fBinterrupt_vector\fP const _vectab[]"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
