.TH "Timer" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer \- Estructura tipo con las acciones del timer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timer\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBTimer_Config_t\fP \fBConfig\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Estructura tipo con las acciones del timer\&. 


.PP
\fBVer también\fP
.RS 4
\fBTimer_Config_t\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBTimer_Config_t\fP Config"
Configuracion del timer 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
