.TH "Timeout_Config" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timeout_Config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timeout_Config\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBTimer_t_ptr\fP \fBTimer\fP"
.br
.ti -1c
.RI "\fBTimeout_Notificacion\fP \fBNotificacion\fP"
.br
.ti -1c
.RI "\fBTimeout_ResetNotificacion\fP \fBResetNotificacion\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBTimeout_Notificacion\fP Notificacion"

.SS "\fBTimeout_ResetNotificacion\fP ResetNotificacion"

.SS "\fBTimer_t_ptr\fP \fBTimer\fP"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
