.TH "Api/N_HAL/Timer/Timer.c" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Api/N_HAL/Timer/Timer.c \- Implementacion de las acciones del timer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <timer\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBTimer_Init\fP (\fBTimer_t_ptr\fP timer)"
.br
.ti -1c
.RI "void \fBTimer_Config_Init\fP (\fBTimer_Config_t_ptr\fP timerConfig, \fBTimer_Numero_e\fP timer, \fBTimer_Canal_e\fP canal, \fBTimer_Modo_e\fP modo, \fBTimer_Interrupcion_e\fP it, uint16_t tiempo)"
.br
.ti -1c
.RI "void \fBTimer_DeInit\fP (\fBTimer_t_ptr\fP timer)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Implementacion de las acciones del timer\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
