.TH "Timeout" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timeout
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timeout\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBTimeout_Config_t\fP \fBConfig\fP"
.br
.ti -1c
.RI "\fBTimeout_Estado_e\fP \fBEstado\fP"
.br
.ti -1c
.RI "uint16_t \fBValorDesborde\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBTimeout_Config_t\fP Config"

.SS "\fBTimeout_Estado_e\fP Estado"

.SS "uint16_t ValorDesborde"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
