.TH "Api/TIMEOUT/Timeout_Config.h" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Api/TIMEOUT/Timeout_Config.h
.SH SYNOPSIS
.br
.PP
\fC#include <stm8s\&.h>\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBTimeout_Config\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBTimeout_Config\fP \fBTimeout_Config_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef volatile uint16_t(* \fBTimeout_Notificacion\fP) (void)"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef void(* \fBTimeout_ResetNotificacion\fP) (uint16_t)"
.br
.RI "<descripcion> "
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
