.TH "Timer_Config" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer_Config \- Estructura tipo para la definicion de la configuracion del timer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Timer_Config\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "\fBTimer_Numero_e\fP \fBTimer\fP"
.br
.ti -1c
.RI "\fBTimer_Canal_e\fP \fBCanal\fP"
.br
.ti -1c
.RI "\fBTimer_Modo_e\fP \fBModo\fP"
.br
.ti -1c
.RI "\fBTimer_Interrupcion_e\fP \fBIT\fP"
.br
.ti -1c
.RI "uint16_t \fBTiempo\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Estructura tipo para la definicion de la configuracion del timer\&. 


.PP
\fBVer también\fP
.RS 4
\fBTimer_Numero_e\fP 
.PP
\fBTimer_Canal_e\fP 
.PP
\fBTimer_Modo_e\fP 
.PP
\fBTimer_Interrupcion_e\fP 
.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "\fBTimer_Canal_e\fP Canal"
Canal del time rusadp 
.SS "\fBTimer_Interrupcion_e\fP IT"
Seleccion uso interrupcion 
.SS "\fBTimer_Modo_e\fP Modo"
Modo de trabajo del timer 
.SS "uint16_t Tiempo"
Tiempo contaje 
.SS "\fBTimer_Numero_e\fP \fBTimer\fP"
\fBTimer\fP fisico usado 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
