.TH "Trama_RX" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trama_RX
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485_Tramas\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBbuffer\fP [\fBRS485_BYTES_BUFFER_RX\fP]"
.br
.ti -1c
.RI "uint8_t \fBptrBuffer\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_RX\fP \fBSecuencia\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "uint8_t buffer[\fBRS485_BYTES_BUFFER_RX\fP]"

.SS "uint8_t ptrBuffer"

.SS "struct \fBFSM_Trama_RX\fP Secuencia"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
