.TH "Trama_BROADCAST" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trama_BROADCAST
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485_Tramas\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBnNodo\fP"
.br
.ti -1c
.RI "\fBRS485_Orden_t\fP \fBOrden\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "uint8_t nNodo"

.SS "\fBRS485_Orden_t\fP Orden"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
