.TH "TRAMAS" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TRAMAS \- TRAMAS
.SH SYNOPSIS
.br
.PP
.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBFSM_Trama_Paso\fP"
.br
.ti -1c
.RI "struct \fBFSM_Trama_RX\fP"
.br
.ti -1c
.RI "struct \fBTrama_RX\fP"
.br
.ti -1c
.RI "struct \fBTrama_TX\fP"
.br
.ti -1c
.RI "struct \fBTrama_BROADCAST\fP"
.br
.ti -1c
.RI "struct \fBBuffer_Tramas\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBRS485_BYTES_N_NODO\fP   2"
.br
.ti -1c
.RI "#define \fBRS485_BYTES_BUFFER_RX\fP   6"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBTrama_RX\fP \fBTrama_RX_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBTrama_TX\fP \fBTrama_TX_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBTrama_BROADCAST\fP \fBTrama_BROADCAST_t\fP"
.br
.RI "<descripcion> "
.ti -1c
.RI "typedef struct \fBBuffer_Tramas\fP \fBBuffer_Tramas_t\fP"
.br
.RI "<descripcion> "
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'defines'"
.PP 
.SS "RS485_BYTES_BUFFER_RX   6"

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SS "RS485_BYTES_N_NODO   2"

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los 'typedefs'"
.PP 
.SS "\fBBuffer_Tramas_t\fP"

.PP
<descripcion> 
.PP
\fBVer también\fP
.RS 4
\fBBuffer_Tramas\fP 
.RE
.PP

.SS "\fBTrama_BROADCAST_t\fP"

.PP
<descripcion> 
.PP
\fBVer también\fP
.RS 4
<referencias> 
.RE
.PP

.SS "\fBTrama_RX_t\fP"

.PP
<descripcion> 
.PP
\fBVer también\fP
.RS 4
<referencias> 
.RE
.PP

.SS "\fBTrama_TX_t\fP"

.PP
<descripcion> 
.PP
\fBVer también\fP
.RS 4
<referencias> 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
