.TH "Typedef" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Typedef \- Typedef
.SH SYNOPSIS
.br
.PP
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBPunteros\fP"
.br
.ti -1c
.RI "\fBEnum\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBHX711\fP \fBHX711_t\fP"
.br
.RI "Crea un tipo de dato \fBHX711\fP para trabajar sobre el Contiene toda la funcionalidad del sensor\&. "
.ti -1c
.RI "typedef struct \fBHX711_Config\fP \fBHX711_Config_t\fP"
.br
.RI "Tipo de dato para definir la configuracion del hx711\&. "
.ti -1c
.RI "typedef struct \fBHX711_Datos\fP \fBHX711_Datos_t\fP"
.br
.RI "Tipo de dato para definir la informacion a almacenar\&. "
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Documentación de los 'typedefs'"
.PP 
.SS "struct _Config \fBHX711_Config_t\fP"

.PP
Tipo de dato para definir la configuracion del hx711\&. 
.SS "struct \fBHX711_Datos\fP \fBHX711_Datos_t\fP"

.PP
Tipo de dato para definir la informacion a almacenar\&. 
.SS "struct \fBHX711\fP \fBHX711_t\fP"

.PP
Crea un tipo de dato \fBHX711\fP para trabajar sobre el Contiene toda la funcionalidad del sensor\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
