.TH "UART_Config" 3 "Jueves, 23 de Septiembre de 2021" "Version 1" "SuperMaceta" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RS485_Config\&.h>\fP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "UART1_StopBits_TypeDef \fBStopBit\fP"
.br
.ti -1c
.RI "UART1_Parity_TypeDef \fBParidad\fP"
.br
.ti -1c
.RI "UART1_WordLength_TypeDef \fBBits\fP"
.br
.ti -1c
.RI "uint32_t \fBBaudios\fP"
.br
.ti -1c
.RI "UART1_Mode_TypeDef \fBModo\fP"
.br
.ti -1c
.RI "UART1_IT_TypeDef \fBTipoInterrupcion\fP"
.br
.ti -1c
.RI "\fBGpio_Config_t\fP \fBP_RX\fP"
.br
.ti -1c
.RI "\fBGpio_Config_t\fP \fBP_TX\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBVer también\fP
.RS 4

.RE
.PP

.SH "Documentación de los campos"
.PP 
.SS "uint32_t Baudios"

.SS "UART1_WordLength_TypeDef Bits"

.SS "UART1_Mode_TypeDef Modo"

.SS "\fBGpio_Config_t\fP P_RX"

.SS "\fBGpio_Config_t\fP P_TX"

.SS "UART1_Parity_TypeDef Paridad"

.SS "UART1_StopBits_TypeDef StopBit"

.SS "UART1_IT_TypeDef TipoInterrupcion"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para SuperMaceta del código fuente\&.
