var annotated_dup =
[
    [ "Buffer_Tramas", "struct_buffer___tramas.html", "struct_buffer___tramas" ],
    [ "DHT11", "struct_d_h_t11.html", "struct_d_h_t11" ],
    [ "DHT11_Config", "struct_d_h_t11___config.html", "struct_d_h_t11___config" ],
    [ "FSM_Trama_Paso", "struct_f_s_m___trama___paso.html", "struct_f_s_m___trama___paso" ],
    [ "FSM_Trama_RX", "struct_f_s_m___trama___r_x.html", "struct_f_s_m___trama___r_x" ],
    [ "Gpio_Config", "struct_gpio___config.html", "struct_gpio___config" ],
    [ "HX711", "struct_h_x711.html", "struct_h_x711" ],
    [ "HX711_Config", "struct_h_x711___config.html", "struct_h_x711___config" ],
    [ "HX711_Datos", "struct_h_x711___datos.html", "struct_h_x711___datos" ],
    [ "interrupt_vector", "structinterrupt__vector.html", "structinterrupt__vector" ],
    [ "RS485", "struct_r_s485.html", "struct_r_s485" ],
    [ "RS485_Config", "struct_r_s485___config.html", "struct_r_s485___config" ],
    [ "RS485_Flags_u", "union_r_s485___flags__u.html", "union_r_s485___flags__u" ],
    [ "RS485_Orden", "struct_r_s485___orden.html", "struct_r_s485___orden" ],
    [ "sDht11_SI", "structs_dht11___s_i.html", "structs_dht11___s_i" ],
    [ "sDht11Datos", "structs_dht11_datos.html", "structs_dht11_datos" ],
    [ "Timeout", "struct_timeout.html", "struct_timeout" ],
    [ "Timeout_Config", "struct_timeout___config.html", "struct_timeout___config" ],
    [ "Timer", "struct_timer.html", "struct_timer" ],
    [ "Timer_Config", "struct_timer___config.html", "struct_timer___config" ],
    [ "Trama_BROADCAST", "struct_trama___b_r_o_a_d_c_a_s_t.html", "struct_trama___b_r_o_a_d_c_a_s_t" ],
    [ "Trama_RX", "struct_trama___r_x.html", "struct_trama___r_x" ],
    [ "Trama_TX", "struct_trama___t_x.html", "struct_trama___t_x" ],
    [ "UART_Config", "struct_u_a_r_t___config.html", "struct_u_a_r_t___config" ]
];